/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright 2020-2023 NXP
 */
#ifndef _DT_BINDINGS_MAILBOX_NXP_LLCE_MB_H_
#define _DT_BINDINGS_MAILBOX_NXP_LLCE_MB_H_

/*
 * LLCE Mailbox Type
 */
#define S32G_LLCE_HIF_CONF_MB		0x0
#define S32G_LLCE_CAN_CONF_MB		0x1
#define S32G_LLCE_CAN_RX_MB		0x2
#define S32G_LLCE_CAN_TX_MB		0x3
#define S32G_LLCE_CAN_LOGGER_MB		0x4
#define S32G_LLCE_CAN_LOGGER_CONFIG_MB	0x5
#define S32G_LLCE_CAN_CORE_CONFIG_MB	0x6

#define LLCE_MB_LINFLEXD_IRQ_0		0x0
#define LLCE_MB_LINFLEXD_IRQ_1		0x1
#define LLCE_MB_LINFLEXD_IRQ_2		0x2
#define LLCE_MB_LINFLEXD_IRQ_3		0x3

#define LLCE_MB_LPSPI_IRQ_0		0x4
#define LLCE_MB_LPSPI_IRQ_1		0x5
#define LLCE_MB_LPSPI_IRQ_2		0x6
#define LLCE_MB_LPSPI_IRQ_3		0x7

#endif
