/* SPDX-License-Identifier: GPL-2.0+ OR BSD-3-Clause */
/*
 * Copyright 2023 NXP
 */

#ifndef S32CC_SCMI_NVMEM_H
#define S32CC_SCMI_NVMEM_H

#define S32CC_SCMI_NVMEM_SOC_LETTER			0x0
#define S32CC_SCMI_NVMEM_SOC_PART_NO			0x1
#define S32CC_SCMI_NVMEM_SOC_MAJOR			0x2
#define S32CC_SCMI_NVMEM_SOC_MINOR			0x3
#define S32CC_SCMI_NVMEM_CORE_MAX_FREQ			0x4
#define S32CC_SCMI_NVMEM_PCIE_DEV_ID			0x5
#define S32CC_SCMI_NVMEM_SERDES_PRESENCE		0x6
#define S32CC_SCMI_NVMEM_SOC_SUBMINOR			0x7
#define S32CC_SCMI_NVMEM_RESET_CAUSE			0x8
#define S32CC_SCMI_NVMEM_LOCKSTEP_ENABLED               0x9
#define S32CC_SCMI_NVMEM_DDR_PMU_IRQ                    0xA

#define S32CC_SCMI_NVMEM_MAX				0xB

#define S32CC_SCMI_NVMEM_CELL_SIZE			0x4

#endif
