# SPDX-License-Identifier: GPL-2.0
# Makefile for Linux PCS drivers

obj-$(CONFIG_PCS_XPCS)		+= pcs-xpcs.o
obj-$(CONFIG_PCS_LYNX)		+= pcs-lynx.o
obj-$(CONFIG_PHY_S32GEN1_SERDES)	+= fsl-s32gen1-xpcs.o
