/* SPDX-License-Identifier: (GPL-2.0+ OR BSD-3-Clause) */
/*
 * SCMI GPIO Protocol
 *
 * Copyright 2022-2023 NXP
 */
#ifndef GPIO_SCMI_PROTOCOL_H
#define GPIO_SCMI_PROTOCOL_H

#define UINT32_C(X)			U32_C(X)
/*
 * SCMI GPIO protocol
 */
#define SCMI_PROTOCOL_ID_GPIO		UINT32_C(0x81)

/*
 * SCMI GPIO protocol version
 */
#define SCMI_PROTOCOL_VERSION_GPIO	UINT32_C(0x10000)

/* Number of GPIO pins per SCMI_GPIO_DESCRIBE slot */
#define SCMI_GPIO_PINS_PER_SLOT		UINT32_C(32)

/*
 * SCMI GPIO commands
 */
#define SCMI_GPIO_DESCRIBE		UINT32_C(0x3)
#define SCMI_GPIO_REQUEST		UINT32_C(0x4)
#define SCMI_GPIO_FREE			UINT32_C(0x5)
#define SCMI_GPIO_SET_VALUE		UINT32_C(0x6)
#define SCMI_GPIO_GET_VALUE		UINT32_C(0x7)
#define SCMI_GPIO_GET_IRQ		UINT32_C(0x8)
#define SCMI_GPIO_IRQ_ENABLE		UINT32_C(0x9)
#define SCMI_GPIO_IRQ_DISABLE		UINT32_C(0xa)
#define SCMI_GPIO_IRQ_MASK		UINT32_C(0xb)
#define SCMI_GPIO_IRQ_UNMASK		UINT32_C(0xc)
#define SCMI_GPIO_GET_DIRECTION		UINT32_C(0xd)
#define SCMI_GPIO_ACK_IRQ		UINT32_C(0xFF)

/* GPIO direction flags */
#define SCMI_GPIO_DIR_OUT		UINT32_C(0)
#define SCMI_GPIO_DIR_IN		UINT32_C(1)

/* Notifications */
#define SCMI_GPIO_IRQ_NOTIFICATION	UINT32_C(0x0)

/* EIRQ type flags */
#define SCMI_GPIO_EIRQ_TYPE_EDGE_RISING		UINT32_C(1)
#define SCMI_GPIO_EIRQ_TYPE_EDGE_FALLING	UINT32_C(2)
#define SCMI_GPIO_EIRQ_TYPE_BOTH		(SCMI_GPIO_EIRQ_TYPE_EDGE_RISING | \
						 SCMI_GPIO_EIRQ_TYPE_EDGE_FALLING)
#define SCMI_GPIO_EIRQ_TYPE_LEVEL_HIGH		UINT32_C(4)
#define SCMI_GPIO_EIRQ_TYPE_LEVEL_LOW		UINT32_C(8)

#endif /* GPIO_SCMI_PROTOCOL_H */
