/* SPDX-License-Identifier: BSD-3-Clause */
/*
 * Copyright 2020-2022 NXP
 */
#ifndef __DT_BINDINGS_SCMI_CLOCK_S32CC_H
#define __DT_BINDINGS_SCMI_CLOCK_S32CC_H

#define S32CC_SCMI_CLK_BASE_ID	0U
#define S32CC_SCMI_CLK(N)		((N) + S32CC_SCMI_CLK_BASE_ID)

/* LINFlexD */
#define S32CC_SCMI_CLK_LINFLEX_XBAR		S32CC_SCMI_CLK(14)
#define S32CC_SCMI_CLK_LINFLEX_LIN		S32CC_SCMI_CLK(15)
/* uSDHC */
#define S32CC_SCMI_CLK_USDHC_AHB		S32CC_SCMI_CLK(32)
#define S32CC_SCMI_CLK_USDHC_MODULE		S32CC_SCMI_CLK(33)
#define S32CC_SCMI_CLK_USDHC_CORE		S32CC_SCMI_CLK(34)

/* RTC */
#define S32CC_SCMI_CLK_RTC_REG			S32CC_SCMI_CLK(55)
#define S32CC_SCMI_CLK_RTC_SIRC			S32CC_SCMI_CLK(56)
#define S32CC_SCMI_CLK_RTC_FIRC			S32CC_SCMI_CLK(57)

#endif /* __DT_BINDINGS_SCMI_CLOCK_S32CC_H */
