/* SPDX-License-Identifier: BSD-3-Clause */
/*
 * Copyright 2020-2022 NXP
 */
#ifndef __DT_BINDINGS_SCMI_CLOCK_S32CC_H
#define __DT_BINDINGS_SCMI_CLOCK_S32CC_H

#define S32CC_SCMI_CLK_BASE_ID	0U
#define S32CC_SCMI_CLK(N)		((N) + S32CC_SCMI_CLK_BASE_ID)

/* FlexCAN */
#define S32CC_SCMI_CLK_FLEXCAN_REG		S32CC_SCMI_CLK(10)
#define S32CC_SCMI_CLK_FLEXCAN_SYS		S32CC_SCMI_CLK(11)
#define S32CC_SCMI_CLK_FLEXCAN_CAN		S32CC_SCMI_CLK(12)
#define S32CC_SCMI_CLK_FLEXCAN_TS		S32CC_SCMI_CLK(13)
/* LINFlexD */
#define S32CC_SCMI_CLK_LINFLEX_XBAR		S32CC_SCMI_CLK(14)
#define S32CC_SCMI_CLK_LINFLEX_LIN		S32CC_SCMI_CLK(15)
/* QSPI */
#define S32CC_SCMI_CLK_QSPI_REG			S32CC_SCMI_CLK(28)
#define S32CC_SCMI_CLK_QSPI_AHB			S32CC_SCMI_CLK(29)
#define S32CC_SCMI_CLK_QSPI_FLASH2X		S32CC_SCMI_CLK(30)
#define S32CC_SCMI_CLK_QSPI_FLASH1X		S32CC_SCMI_CLK(31)
/* uSDHC */
#define S32CC_SCMI_CLK_USDHC_AHB		S32CC_SCMI_CLK(32)
#define S32CC_SCMI_CLK_USDHC_MODULE		S32CC_SCMI_CLK(33)
#define S32CC_SCMI_CLK_USDHC_CORE		S32CC_SCMI_CLK(34)

/* RTC */
#define S32CC_SCMI_CLK_RTC_REG			S32CC_SCMI_CLK(55)
#define S32CC_SCMI_CLK_RTC_SIRC			S32CC_SCMI_CLK(56)
#define S32CC_SCMI_CLK_RTC_FIRC			S32CC_SCMI_CLK(57)
/* SWT */
#define S32CC_SCMI_CLK_SWT_MODULE		S32CC_SCMI_CLK(58)
#define S32CC_SCMI_CLK_SWT_COUNTER		S32CC_SCMI_CLK(59)
/* STM */
#define S32CC_SCMI_CLK_STM_MODULE		S32CC_SCMI_CLK(60)
#define S32CC_SCMI_CLK_STM_REG			S32CC_SCMI_CLK(61)
/* PIT */
#define S32CC_SCMI_CLK_PIT_MODULE		S32CC_SCMI_CLK(62)
#define S32CC_SCMI_CLK_PIT_REG			S32CC_SCMI_CLK(63)
/* eDMA */
#define S32CC_SCMI_CLK_EDMA_MODULE		S32CC_SCMI_CLK(64)
#define S32CC_SCMI_CLK_EDMA_AHB			S32CC_SCMI_CLK(65)

#endif /* __DT_BINDINGS_SCMI_CLOCK_S32CC_H */
